name: Run WELA Audit

on:
  push:
    branches: [ "*" ]
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ windows-2019, windows-2022, windows-2025, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout WELA repository
        uses: actions/checkout@v4
        with:
          repository: Yamato-Security/WELA
          path: WELA

      - name: Run configure bat(ASD)
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          cd bat
          ./ASD.bat

      - name: Run configure bat(MS Client)
        if: ${{ matrix.os == 'windows-2025' }}
        run: |
          cd bat
          ./Microsoft_Client.bat

      - name: Run configure bat(MS Server)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd bat
          ./Microsoft_Server.bat

      - name: Run WELA.ps1 audit-settings(Default)
        if: ${{ matrix.os == 'windows-2019' }}
        run: |
          cd WELA
          ./WELA.ps1 audit-settings

      - name: Run WELA.ps1 audit-settings(ASD)
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          cd WELA
          ./WELA.ps1 audit-settings -Baseline ASD

      - name: Run WELA.ps1 audit-settings(MS Client)
        if: ${{ matrix.os == 'windows-2025' }}
        run: |
          cd WELA
          ./WELA.ps1 audit-settings -Baseline Microsoft_Client

      - name: Run WELA.ps1 audit-settings(MS Server)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd WELA
          ./WELA.ps1 audit-settings -Baseline Microsoft_Server

      - name: Run WELA.ps1 audit-filesize
        run: |
          cd WELA
          ./WELA.ps1 audit-filesize

      - name: Convert audit csv result (Default)
        if: ${{ matrix.os == 'windows-2019' }}
        run: |
          # WELA-Audit-Result.csvのRecommendedSetting列を空白にする
          $auditCsvPath = "./WELA/WELA-Audit-Result.csv"
          $auditData = Import-Csv $auditCsvPath
          $auditData | ForEach-Object { $_.RecommendedSetting = "" }
          $auditData | Export-Csv $auditCsvPath -NoTypeInformation -Encoding UTF8

      - name: Convert file size csv result
        run: |      
          # WELA-FileSize-Result.csvのRecommended列を空白にする
          $fileSizeCsvPath = "./WELA/WELA-FileSize-Result.csv"
          $fileSizeData = Import-Csv $fileSizeCsvPath
          $fileSizeData | ForEach-Object { $_.Recommended = "" }
          $fileSizeData | Export-Csv $fileSizeCsvPath -NoTypeInformation -Encoding UTF8

      - name: Move WELA result files (Default)
        if: ${{ matrix.os == 'windows-2019' }}
        run: |
          cd WELA
          Copy-Item *.csv ../data/Windows_Default/ -Force

      - name: Move WELA result files (ASD)
        if: ${{ matrix.os == 'windows-2022' }}
        run: |
          cd WELA
          Copy-Item *.csv ../data/Australian_Signals_Directorate/ -Force

      - name: Move WELA result files (Microsoft_Client)
        if: ${{ matrix.os == 'windows-2025' }}
        run: |
          cd WELA
          Copy-Item *.csv ../data/Microsoft_Client/ -Force

      - name: Move WELA result files (Microsoft_Server)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd WELA
          Copy-Item *.csv ../data/Microsoft_Server/ -Force

      - name: Delete WELA repo
        run: |
          Remove-Item -Recurse -Force WELA

      - name: Pull Git repo
        run: |
          git pull origin main

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply changes

      - name: Checkout WELA repository
        if: ${{ matrix.os == 'windows-2019' }}
        uses: actions/checkout@v4
        with:
          repository: Yamato-Security/WELA
          path: WELA

      - name: Run configure bat(YamatoSecurity)
        if: ${{ matrix.os == 'windows-2019' }}
        run: |
          cd bat
          ./YamatoSecurity.bat

      - name: Run WELA.ps1 audit-settings
        if: ${{ matrix.os == 'windows-2019' }}
        run: |
          cd WELA
          ./WELA.ps1 audit-settings

      - name: Run WELA.ps1 audit-filesize
        if: ${{ matrix.os == 'windows-2019' }}
        run: |
          cd WELA
          ./WELA.ps1 audit-filesize

      - name: Move WELA result files (YamatoSecurity)
        if: ${{ matrix.os == 'windows-2019' }}
        run: |
          cd WELA
          Copy-Item *.csv ../data/YamatoSecurity/ -Force

      - name: Delete WELA repo
        if: ${{ matrix.os == 'windows-2019' }}
        run: |
          Remove-Item -Recurse -Force WELA

      - name: Pull Git repo
        if: ${{ matrix.os == 'windows-2019' }}
        run: |
          git pull origin main

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ matrix.os == 'windows-2019' }}
        with:
          commit_message: Apply changes